# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wmpf_debug.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'wmpf_debug.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10wmpf_debug.proto\x12\x11mmbizwxadevremote\"u\n\x1aWARemoteDebug_DebugMessage\x12\x0b\n\x03seq\x18\x01 \x01(\r\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x14\n\x0c\x63ompressAlgo\x18\x05 \x01(\r\x12\x14\n\x0coriginalSize\x18\x06 \x01(\r\"R\n\x1cWARemoteDebug_ChromeDevtools\x12\x0c\n\x04opId\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x13\n\x0bjscontextId\x18\x03 \x01(\t\"X\n\"WARemoteDebug_ChromeDevtoolsResult\x12\x0c\n\x04opId\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x13\n\x0bjscontextId\x18\x03 \x01(\t\"w\n\x1aWARemoteDebug_SetupContext\x12\x13\n\x0bjscontextId\x18\x01 \x01(\t\x12\r\n\x05\x61ppid\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x12\n\nsdkVersion\x18\x05 \x01(\t\"O\n\x1bWARemoteDebug_CustomMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wmpf_debug_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WAREMOTEDEBUG_DEBUGMESSAGE']._serialized_start=39
  _globals['_WAREMOTEDEBUG_DEBUGMESSAGE']._serialized_end=156
  _globals['_WAREMOTEDEBUG_CHROMEDEVTOOLS']._serialized_start=158
  _globals['_WAREMOTEDEBUG_CHROMEDEVTOOLS']._serialized_end=240
  _globals['_WAREMOTEDEBUG_CHROMEDEVTOOLSRESULT']._serialized_start=242
  _globals['_WAREMOTEDEBUG_CHROMEDEVTOOLSRESULT']._serialized_end=330
  _globals['_WAREMOTEDEBUG_SETUPCONTEXT']._serialized_start=332
  _globals['_WAREMOTEDEBUG_SETUPCONTEXT']._serialized_end=451
  _globals['_WAREMOTEDEBUG_CUSTOMMESSAGE']._serialized_start=453
  _globals['_WAREMOTEDEBUG_CUSTOMMESSAGE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
